name: Run tests

permissions:
  id-token: write
  contents: write
  pull-requests: write
  pages: write

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser engine'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
      environment:
        description: 'Select environment'
        required: true
        default: 'prod'
        type: choice
        options:
          - dev
          - staging
          - prod
      test_suite:
        description: 'Select test suite'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.50.0-noble
      options: --user 1001
    env:
      PLAYWRIGHT_BROWSER: ${{ github.event.inputs.browser }}
      TARGET_ENVIRONMENT: ${{ github.event.inputs.environment }}
      TEST_SUITE: ${{ github.event.inputs.test_suite }}
      USER_BYPASS_CHECK_TOKEN: ${{ secrets.USER_BYPASS_CHECK_TOKEN }}
      PLR_HEADLESS: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: "gradle"

      - name: Run tests
        run: |
          ./gradlew clean test \
            -DincludeTags=${{ env.TEST_SUITE }}

      - name: Upload Playwright Artifacts (Screenshots & Videos)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-artifacts
          path: test-results/

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: build/allure-results

  report:
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - uses: actions/checkout@v4

      - name: Download Playwright Artifacts (Screenshots & Videos)
        uses: actions/download-artifact@v4
        with:
          name: playwright-artifacts
          path: test-results/

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: build/allure-results

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.12
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
